const meals = [
  // BREAKFAST OPTIONS
  {
    id: "pap-akara",
    name: "Pap & Akara",
    vegetarian: true,
    contains: [],
    mealType: "breakfast",
    calories: 420,
    carbohydrate: 60,
    protein: 14,
    fat: 12,
    image: "/images/akarapap.jpg",
    instructions: "Serve hot pap with fried akara balls.",
    ingredients: ["Pap", "Beans", "Onion", "Palm oil or vegetable oil", "Salt"]
  },
  {
    id: "moi-moi-pap",
    name: "Moi Moi & Pap",
    vegetarian: true,
    contains: [],
    mealType: "breakfast",
    calories: 380,
    carbohydrate: 55,
    protein: 16,
    fat: 9,
    image: "/images/moi&pap.jpg",
    instructions: "Steam moi moi and serve with hot pap.",
    ingredients: ["Beans", "Pepper", "Onion", "Palm oil", "Pap"]
  },
  {
    id: "bread-akara",
    name: "Bread & Akara",
    vegetarian: true,
    contains: ["gluten"],
    mealType: "breakfast",
    calories: 450,
    carbohydrate: 65,
    protein: 15,
    fat: 14,
    image: "/images/break&akara.jpg",
    instructions: "Stuff akara inside soft agege bread.",
    ingredients: ["Bread", "Beans", "Onion", "Vegetable oil", "Salt"]
  },
  {
    id: "yam-egg-sauce",
    name: "Yam & Egg Sauce",
    vegetarian: true,
    contains: ["egg"],
    mealType: "breakfast",
    calories: 500,
    carbohydrate: 70,
    protein: 18,
    fat: 15,
    image: "/images/yam&eggsauce.jpg",
    instructions: "Boil yam and serve with fried egg sauce.",
    ingredients: ["Yam", "Eggs", "Tomatoes", "Onion", "Vegetable oil"]
  },
  {
    id: "ogi-or-akamu-with-milk",
    name: "Ogi or Akamu with Milk",
    vegetarian: true,
    contains: ["dairy"],
    mealType: "breakfast",
    calories: 350,
    carbohydrate: 55,
    protein: 12,
    fat: 8,
    image: "/images/ogi.jpg",
    instructions: "Serve pap with milk and sugar (optional).",
    ingredients: ["Pap (fermented maize)", "Milk", "Sugar (optional)"]
  },
  {
    id: "plantain-frittata",
    name: "Plantain Frittata",
    vegetarian: true,
    contains: ["egg"],
    mealType: "breakfast",
    calories: 480,
    carbohydrate: 50,
    protein: 20,
    fat: 16,
    image: "/images/plantainfri.jpg",
    instructions: "Bake sliced plantain with eggs and vegetables.",
    ingredients: ["Plantain", "Eggs", "Onion", "Tomatoes", "Vegetable oil"]
  },
  {
    id: "beans-cake-akara-custard",
    name: "Beans Cake (Akara) & Custard",
    vegetarian: true,
    contains: ["dairy"],
    mealType: "breakfast",
    calories: 430,
    carbohydrate: 58,
    protein: 14,
    fat: 13,
    image: "/images/akara&custard.jpg",
    instructions: "Serve akara balls with custard.",
    ingredients: ["Beans", "Onion", "Vegetable oil", "Custard powder", "Milk"]
  },
  {
    id: "boiled-sweet-potatoes-sauce",
    name: "Boiled Sweet Potatoes & Sauce",
    vegetarian: true,
    contains: [],
    mealType: "breakfast",
    calories: 410,
    carbohydrate: 62,
    protein: 12,
    fat: 10,
    image: "/images/potatoe&sauce.jpg",
    instructions: "Boil potatoes and serve with pepper sauce.",
    ingredients: ["Sweet potatoes", "Palm oil", "Onion", "Pepper", "Tomatoes"]
  },
  {
    id: "nkwobi-light-portion",
    name: "Nkwobi (light portion)",
    vegetarian: false,
    contains: ["beef"],
    mealType: "breakfast",
    calories: 390,
    carbohydrate: 35,
    protein: 20,
    fat: 14,
    image: "/images/nkwobi.jpg",
    instructions: "Cow foot pepper soup, small portion.",
    ingredients: ["Cow foot", "Palm oil", "Utazi leaves", "Onion", "Pepper"]
  },
  {
    id: "tea-bread-with-egg",
    name: "Tea & Bread with Egg",
    vegetarian: true,
    contains: ["gluten", "egg", "dairy"],
    mealType: "breakfast",
    calories: 440,
    carbohydrate: 60,
    protein: 18,
    fat: 12,
    image: "/images/bread&egg.jpg",
    instructions: "Serve hot tea with buttered bread and fried egg.",
    ingredients: ["Tea", "Bread", "Eggs", "Butter", "Milk"]
  },

  // LUNCH OPTIONS
  {
    id: "jollof-rice-chicken",
    name: "Jollof Rice & Chicken",
    vegetarian: false,
    contains: ["chicken"],
    mealType: "lunch",
    calories: 650,
    carbohydrate: 85,
    protein: 32,
    fat: 20,
    image: "/images/jollofrice.jpg",
    instructions: "Serve jollof rice with grilled chicken.",
    ingredients: ["Rice", "Tomatoes", "Pepper", "Onion", "Chicken", "Vegetable oil"]
  },
  {
    id: "fried-rice-plantain",
    name: "Fried Rice & Plantain",
    vegetarian: false,
    contains: ["chicken"],
    mealType: "lunch",
    calories: 600,
    carbohydrate: 80,
    protein: 22,
    fat: 18,
    image: "/images/friedrice&plantain.jpg",
    instructions: "Serve fried rice with fried plantain.",
    ingredients: ["Rice", "Mixed vegetables", "Chicken stock", "Plantain", "Vegetable oil"]
  },
  {
    id: "efo-riro-semovita",
    name: "Efo Riro & Semovita",
    vegetarian: true,
    contains: ["gluten"],
    mealType: "lunch",
    calories: 700,
    carbohydrate: 90,
    protein: 30,
    fat: 22,
    image: "/images/eforiro.jpg",
    instructions: "Serve efo riro with semo.",
    ingredients: ["Spinach/ugu leaves", "Palm oil", "Tomatoes", "Pepper", "Semovita"]
  },
  {
    id: "egusi-soup-pounded-yam",
    name: "Egusi Soup & Pounded Yam",
    vegetarian: false,
    contains: ["fish"],
    mealType: "lunch",
    calories: 750,
    carbohydrate: 95,
    protein: 28,
    fat: 25,
    image: "/images/egusi&poundedyam.jpg",
    instructions: "Serve egusi soup with pounded yam.",
    ingredients: ["Egusi (melon seeds)", "Palm oil", "Spinach", "Yam", "Stockfish"]
  },
  {
    id: "okra-soup-fufu",
    name: "Okra Soup & Fufu",
    vegetarian: false,
    contains: ["shellfish"],
    mealType: "lunch",
    calories: 680,
    carbohydrate: 88,
    protein: 26,
    fat: 20,
    image: "/images/okoroandfufu.jpg",
    instructions: "Serve okra soup with cassava fufu.",
    ingredients: ["Okra", "Palm oil", "Crayfish", "Cassava fufu", "Pepper"]
  },
  {
    id: "beans-plantain",
    name: "Beans & Plantain",
    vegetarian: true,
    contains: [],
    mealType: "lunch",
    calories: 550,
    carbohydrate: 80,
    protein: 22,
    fat: 10,
    image: "/images/beans&plantain.jpg",
    instructions: "Serve beans porridge with fried plantain.",
    ingredients: ["Beans", "Palm oil", "Onion", "Plantain"]
  },
  {
    id: "ofada-rice-ayamase-sauce",
    name: "Ofada Rice & Ayamase Sauce",
    vegetarian: false,
    contains: ["beef"],
    mealType: "lunch",
    calories: 720,
    carbohydrate: 95,
    protein: 30,
    fat: 24,
    image: "/images/ayameseandofada.jpg",
    instructions: "Serve local ofada rice with spicy ayamase sauce.",
    ingredients: ["Ofada rice", "Green pepper", "Locust beans", "Palm oil", "Beef"]
  },
  {
    id: "banga-soup-starch",
    name: "Banga Soup & Starch",
    vegetarian: false,
    contains: ["fish", "beef"],
    mealType: "lunch",
    calories: 760,
    carbohydrate: 92,
    protein: 27,
    fat: 28,
    image: "/images/banga&starch.jpg",
    instructions: "Serve banga soup with starch swallow.",
    ingredients: ["Palm nuts", "Spices", "Catfish", "Beef", "Starch"]
  },
  {
    id: "afang-soup-garri",
    name: "Afang Soup & Garri",
    vegetarian: false,
    contains: ["fish"],
    mealType: "lunch",
    calories: 740,
    carbohydrate: 96,
    protein: 29,
    fat: 26,
    image: "/images/afang&garri.jpg",
    instructions: "Serve afang soup with garri.",
    ingredients: ["Afang leaves", "Waterleaf", "Palm oil", "Garri", "Stockfish"]
  },
  {
    id: "oha-soup-pounded-yam",
    name: "Oha Soup & Pounded Yam",
    vegetarian: false,
    contains: ["beef"],
    mealType: "lunch",
    calories: 730,
    carbohydrate: 92,
    protein: 28,
    fat: 25,
    image: "/images/ohaandpoundedyam.jpg",
    instructions: "Serve oha soup with pounded yam.",
    ingredients: ["Oha leaves", "Palm oil", "Cocoyam", "Yam", "Beef"]
  },

  // DINNER OPTIONS
  {
    id: "beans-porridge",
    name: "Beans Porridge",
    vegetarian: true,
    contains: [],
    mealType: "dinner",
    calories: 500,
    carbohydrate: 70,
    protein: 22,
    fat: 12,
    image: "/images/beans.jpg",
    instructions: "Serve beans porridge with dodo.",
    ingredients: ["Beans", "Palm oil", "Onion", "Pepper", "Plantain"]
  },
  {
    id: "yam-porridge-asaro",
    name: "Yam Porridge (Asaro)",
    vegetarian: true,
    contains: [],
    mealType: "dinner",
    calories: 540,
    carbohydrate: 78,
    protein: 14,
    fat: 16,
    image: "/images/yamporridge.jpg",
    instructions: "Cook yam porridge with palm oil & veggies.",
    ingredients: ["Yam", "Palm oil", "Pepper", "Onion", "Vegetables"]
  },
  {
    id: "ewa-agoyin-bread",
    name: "Ewa Agoyin & Bread",
    vegetarian: true,
    contains: ["gluten"],
    mealType: "dinner",
    calories: 520,
    carbohydrate: 74,
    protein: 18,
    fat: 14,
    image: "/images/ewa.jpg",
    instructions: "Serve mashed beans with agege bread.",
    ingredients: ["Beans", "Palm oil", "Pepper", "Onion", "Bread"]
  },
  {
    id: "okpa-steamed-bambara-nut-cake",
    name: "Okpa (Steamed Bambara Nut Cake)",
    vegetarian: true,
    contains: [],
    mealType: "dinner",
    calories: 450,
    carbohydrate: 65,
    protein: 16,
    fat: 11,
    image: "/images/okpa.jpg",
    instructions: "Steam okpa in banana leaves.",
    ingredients: ["Bambara nut flour", "Palm oil", "Onion", "Pepper"]
  },
  {
    id: "nkwobi-dinner-portion",
    name: "Nkwobi (Dinner Portion)",
    vegetarian: false,
    contains: ["beef"],
    mealType: "dinner",
    calories: 600,
    carbohydrate: 40,
    protein: 32,
    fat: 28,
    image: "/images/nkwobi.jpg",
    instructions: "Serve spiced cow foot with palm oil sauce.",
    ingredients: ["Cow foot", "Palm oil", "Utazi leaves", "Onion", "Seasoning"]
  },
  {
    id: "abacha-african-salad",
    name: "Abacha (African Salad)",
    vegetarian: false,
    contains: ["fish"],
    mealType: "dinner",
    calories: 490,
    carbohydrate: 68,
    protein: 16,
    fat: 15,
    image: "/images/abacha.jpg",
    instructions: "Mix cassava flakes with ugba, fish & palm oil.",
    ingredients: ["Cassava flakes (abacha)", "Ugba", "Palm oil", "Dry fish", "Pepper"]
  },
  {
    id: "fish-pepper-soup",
    name: "Fish Pepper Soup",
    vegetarian: false,
    contains: ["fish"],
    mealType: "dinner",
    calories: 420,
    carbohydrate: 10,
    protein: 36,
    fat: 12,
    image: "/images/fish-pepper.jpg",
    instructions: "Serve hot fish pepper soup with yam (optional).",
    ingredients: ["Fish (catfish/tilapia)", "Pepper", "Spices", "Onion", "Yam (optional)"]
  },
  {
    id: "steamed-white-rice-vegetable-sauce",
    name: "Steamed White Rice & Vegetable Sauce",
    vegetarian: true,
    contains: [],
    mealType: "dinner",
    calories: 530,
    carbohydrate: 76,
    protein: 18,
    fat: 14,
    image: "/images/rice&vegetable.jpg",
    instructions: "Serve plain rice with spicy vegetable sauce.",
    ingredients: ["Rice", "Vegetables", "Palm oil", "Pepper", "Onion"]
  },
  {
    id: "plantain-porridge",
    name: "Plantain Porridge",
    vegetarian: true,
    contains: [],
    mealType: "dinner",
    calories: 510,
    carbohydrate: 72,
    protein: 16,
    fat: 13,
    image: "/images/platain-porridge.jpg",
    instructions: "Cook unripe plantain porridge with vegetables.",
    ingredients: ["Unripe plantain", "Palm oil", "Pepper", "Onion", "Vegetables"]
  },
  {
    id: "ogbono-soup-eba",
    name: "Ogbono Soup & Eba",
    vegetarian: false,
    contains: ["fish"],
    mealType: "dinner",
    calories: 720,
    carbohydrate: 95,
    protein: 26,
    fat: 24,
    image: "/images/ogbono-eba.jpg",
    instructions: "Serve ogbono soup with eba.",
    ingredients: ["Ogbono seeds", "Palm oil", "Stockfish", "Eba (garri)", "Pepper"]
  }
];

export default meals;
